server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          #user service
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
          #plans service
        - id: plans-service
          uri: http://localhost:9090
          predicates:
            - Path=/plans/**
          filters:
           # - StripPrefix=1 # Remueve el prefijo '/plans' para enviar correctamente la solicitud al servicio
            - name: AuthenticationFilter


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
